load_module modules/ngx_http_upstream_identity_module.so;

worker_processes  1;
error_log logs/error.log notice;
pid logs/nginx.pid;

events {
    worker_connections 1024;
}

http {
    access_log logs/access.log;

    upstream backend_tls {
        server 127.0.0.1:9443;
    }

    server {
        listen 8080;

        location / {
            upstream_identity_monitor on;

            proxy_ssl_verify off;
            proxy_ssl_server_name on;
            proxy_ssl_name backend.test;

            proxy_pass https://backend_tls;
        }
    }
}
